name: Android CI on Pull Request

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Delete distribution page
        run: |
          curl \
            -X DELETE \
            -F "token=${{secrets.DEPLOYGATE_TOKEN}}" \
            -F "distribution_name=$GITHUB_HEAD_REF" \
            https://deploygate.com/api/users/${{secrets.DEPLOYGATE_USER}}/platforms/android/apps/com.horie1024.githubactionssample/distributions
